name: beam
channels:
  - conda-forge
dependencies:
  - python
  - GDAL
  - Fiona
  - rasterio
  - fastapi
  - uvicorn
  - affine
  - anyio
  - asgiref
  - attrs
  - catalogue
  - certifi
  - charset-normalizer
  - click
  - click-plugins
  - cligj
  - colorama
  - cycler
  - cymem
  - fastai::fastai=2.5.3
  - fastcore
  - fastdownload
  - fastprogress
  - fonttools
  - geopandas
  - h11
  - idna
  - Jinja2
  - joblib
  - kiwisolver
  - langcodes
  - MarkupSafe
  - matplotlib
  - munch
  - murmurhash
  - natsort
  - numpy
  - packaging
  - pandas
  - pathy
  - Pillow
  - preshed
  - pydantic
  - pyparsing
  - pyproj
  - python-dateutil
  - pytz
  - PyYAML
  - requests
  - scikit-learn
  - scipy
  - six
  - sniffio
  - snuggs
  - spacy
  - spacy-legacy
  - spacy-loggers
  - srsly
  - starlette
  - thinc
  - threadpoolctl
  - tqdm
  - typer
  - typing_extensions
  - urllib3
  - wasabi
  - pytorch::pytorch=1.11.0
  - pytorch::torchvision=0.12.0
  - nvidia::cudatoolkit=11.3.0
  - pip
  - pip:
    - SemTorch==0.1.1
    - smart-open==5.2.1
    - blis==0.7.6
    - Shapely==1.8.1.post1
