name: beam
channels:
  - conda-forge
dependencies:
  - pytorch::pytorch=1.13.1
  - pytorch::torchvision=0.14.1
  - pytorch::pytorch-cuda
  - fastai::fastcore
  - fastai::fastai
  - GDAL
  - Fiona
  - rasterio
  - fastapi
  - uvicorn
  - geopandas
  - numpy
  - pytz
  - IPython
  - scikit-learn
  - natsort
  - opencv
  - pip
  - pip:
    - SemTorch
    - Shapely
