echo "Installation starting ..." ^
 &&  pip install ./libs/GDAL-3.4.1-cp39-cp39-win_amd64.whl ^
 &&  pip install ./libs/Fiona-1.8.21-cp39-cp39-win_amd64.whl ^
 &&  pip install ./libs/rasterio-1.2.10-cp39-cp39-win_amd64.whl ^
 &&  pip install fastapi==0.75.0 ^
 &&  pip install uvicorn==0.17.6 ^
 &&  pip install affine==2.3.0 ^
 &&  pip install anyio==3.5.0 ^
 &&  pip install asgiref==3.5.0 ^
 &&  pip install attrs==21.4.0 ^
 &&  pip install blis==0.7.6 ^
 &&  pip install catalogue==2.0.6 ^
 &&  pip install certifi==2021.10.8 ^
 &&  pip install charset-normalizer==2.0.12 ^
 &&  pip install click==8.0.4 ^
 &&  pip install click-plugins==1.1.1 ^
 &&  pip install cligj==0.7.2 ^
 &&  pip install colorama==0.4.4 ^
 &&  pip install cycler==0.11.0 ^
 &&  pip install cymem==2.0.6 ^
 &&  pip install fastai==2.5.3 ^
 &&  pip install fastcore==1.3.29 ^
 &&  pip install fastdownload==0.0.5 ^
 &&  pip install fastprogress==1.0.2 ^
 &&  pip install fonttools==4.30.0 ^
 &&  pip install geopandas==0.10.2 ^
 &&  pip install h11==0.13.0 ^
 &&  pip install idna==3.3 ^
 &&  pip install Jinja2==3.0.3 ^
 &&  pip install joblib==1.1.0 ^
 &&  pip install kiwisolver==1.3.2 ^
 &&  pip install langcodes==3.3.0 ^
 &&  pip install MarkupSafe==2.1.0 ^
 &&  pip install matplotlib==3.5.1 ^
 &&  pip install munch==2.5.0 ^
 &&  pip install murmurhash==1.0.6 ^
 &&  pip install natsort==8.1.0 ^
 &&  pip install numpy==1.22.3 ^
 &&  pip install packaging==21.3 ^
 &&  pip install pandas==1.4.1 ^
 &&  pip install pathy==0.6.1 ^
 &&  pip install Pillow==9.0.1 ^
 &&  pip install preshed==3.0.6 ^
 &&  pip install pydantic==1.8.2 ^
 &&  pip install pyparsing==3.0.7 ^
 &&  pip install pyproj==3.3.0 ^
 &&  pip install python-dateutil==2.8.2 ^
 &&  pip install pytz==2021.3 ^
 &&  pip install PyYAML==6.0 ^
 &&  pip install requests==2.27.1 ^
 &&  pip install scikit-learn==1.0.2 ^
 &&  pip install scipy==1.8.0 ^
 &&  pip install Shapely==1.8.1.post1 ^
 &&  pip install six==1.16.0 ^
 &&  pip install smart-open==5.2.1 ^
 &&  pip install sniffio==1.2.0 ^
 &&  pip install snuggs==1.4.7 ^
 &&  pip install spacy==3.2.3 ^
 &&  pip install spacy-legacy==3.0.9 ^
 &&  pip install spacy-loggers==1.0.1 ^
 &&  pip install srsly==2.4.2 ^
 &&  pip install starlette==0.17.1 ^
 &&  pip install thinc==8.0.13 ^
 &&  pip install threadpoolctl==3.1.0 ^
 &&  pip install tqdm==4.63.0 ^
 &&  pip install typer==0.4.0 ^
 &&  pip install typing_extensions==4.1.1 ^
 &&  pip install urllib3==1.26.8 ^
 &&  pip install wasabi==0.9.0 ^
 &&  pip uninstall -y torch ^
 &&  pip uninstall -y torchvision ^
 &&  pip install "https://download.pytorch.org/whl/cu113/torch-1.10.2%%2Bcu113-cp39-cp39-win_amd64.whl" ^
 &&  pip install "https://download.pytorch.org/whl/cu113/torchvision-0.11.3%%2Bcu113-cp39-cp39-win_amd64.whl" ^
 &&  pip install SemTorch==0.1.1 ^
 &&  echo " Installation finished." ^
 &&  pause 