# GENERAL SETTINGS
codes: ["Background", "Building"]
seed: 2022
# DATA SETTINGS
test_size: 0.2
tiling:
  distance_weighting: false
  erosion: true
  tile_size: 512
# MODEL SETTINGS
model_version: HRNet_20240215-1703 # for inference or fine-tuning
train:
  architecture: HRNet
  backbone: hrnet_w30
  early_stopping: false
  epochs: 300
  loss_function: None
  finetune: false
training: true
