# GENERAL SETTINGS
codes: ["Background", "Building"]
seed: 2022
# DATA SETTINGS
test_size: 0.2
tiling:
  distance_weighting: false
  erosion: true
  tile_size: 512
# MODEL SETTINGS
model_version: 20240215_unet_retrained_resnet50 # needed for infer_settlements.py script
training: false
