# GENERAL SETTINGS
codes: ["Background", "Building"]
seed: 2022
# DATA SETTINGS
test_size: 0.2
tiling:
  tile_labels: false
  distance_weighting: false
  erosion: true
  tile_size: 512
# MODEL SETTINGS
model_version: U-Net_20240221-1602 # required for evaluation or retraining
train:
  architecture: U-Net
  backbone: resnet50
  early_stopping: false
  epochs: 300
  loss_function: None
  pretrained: true
training: true
