name: beam
channels:
  - pytorch
  - fastai
  - nvidia
  - conda-forge
dependencies:
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - fastai
  - colorlog
  - geopandas
  - fastapi
  - jupyterlab
  - uvicorn
  - rasterio
  - ipython
  - opencv
  - natsort
  - pillow
  - pip
  - pip:
      - torchaudio==0.13.1
      - torchvision==0.14.1    
      - semtorch
