name: beam-lightning
channels:
  - pytorch
  - fastai
  - nvidia
  - conda-forge
dependencies:
  - python
  - numpy 
  - pytorch
  - pytorch-cuda=11.8
  - lightning
  - segmentation-models-pytorch
  - torchgeo
  - albumentations
  - tensorboard
  - colorlog
  - geopandas
  - fastapi
  - jupyterlab
  - uvicorn
  - rasterio
  - rioxarray
  - ipython
  - opencv
  - natsort
  - pillow
  - pytest
  - pip

