name: beam
channels:
  - pytorch
  - fastai
  - nvidia
  - conda-forge
dependencies:
  - numpy=1.23.5 # numpy <1.24 required for semtorch
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - fastai=2.7.14
  - tensorboard
  - colorlog
  - geopandas
  - fastapi
  - jupyterlab
  - uvicorn
  - rasterio
  - rioxarray
  - ipython
  - opencv
  - natsort
  - pillow
  - pytest
  - pip
  - pip:
      - semtorch
