---
# Template configuration for experiments.
# Update for general changes, or make a copy for experiments.
# GENERAL SETTINGS
codes: ["Background", "Building"]
dirs:
  eval: eval
  image_tiles: tiles/images
  images: images
  labels: labels
  mask_tiles: tiles/masks
  models: models
  predictions: predict/masks
  shapefiles: predict/shapefiles
  test: tiles/test
  tiles: tiles
  train: tiles/train
# DATA SETTINGS
erosion: true
labels_type: open_buildings_dataset
root_dir: F:/ethekwini
seed: 2022
test:
  model_name: U-Net_20231218-1843.pkl
test_size: 0.2
tile_size: 512
# MODEL SETTINGS
train:
  architecture: U-Net
  backbone: resnet18
  epochs: 30
  loss_function: None
training: true
