---
# Template configuration for experiments.
# Update for general changes, or make a copy for experiments.
# GENERAL SETTINGS
codes: ["Background", "Building"]
# DATA SETTINGS
tiling:
  distance_weighting: false
  create_tile_shp: false
  erosion: true
  tile_size: 512
root_dir: F:/dev_versions/SanJose_model
seed: 2022
test:
  model_version: HRNet_20240130-1021
test_size: 0.2
# MODEL SETTINGS
train:
  architecture: HRNet
  backbone: hrnet_w30
  epochs: 300
  loss_function: None
training: true
