---
# Template configuration for experiments.
# Update for general changes, or make a copy for experiments.
# GENERAL SETTINGS
codes: ["Background", "Building"]
dirs:
  eval: eval
  image_tiles: tiles/images
  images: images
  labels: labels
  mask_tiles: tiles/masks
  label_tiles: tiles/labels
  models: models
  predictions: predict/masks
  shapefiles: predict/shapefiles
  test: tiles/test
  tiles: tiles
  train: tiles/train
# DATA SETTINGS
erosion: true
root_dir: F:/SanSalvador_model
seed: 2022
test:
  model_name: HRNet_20240110-1625.pkl
test_size: 0.2
tile_size: 256
# MODEL SETTINGS
train:
  architecture: HRNet
  backbone: hrnet_w18
  epochs: 300
  loss_function: None
training: true
