---
# Template configuration for experiments.
# Update for general changes, or make a copy for experiments.
# GENERAL SETTINGS
codes: ["Background", "Building"]
# DATA SETTINGS
erosion: true
root_dir: F:/SanJose_labeling
seed: 2022
test:
  model_version: U-Net_20241117-1410
test_size: 0.2
tile_size: 128
# MODEL SETTINGS
train:
  architecture: U-Net
  backbone: resnet18
  epochs: 30
  loss_function: None
training: false
