---
# Template configuration for experiments.
# Update for general changes, or make a copy for experiments.
# GENERAL SETTINGS
codes: ["Background", "Building"]
# DATA SETTINGS
tiling:
  distance_weighting: true
  create_tile_shp: false
  erosion: true
  tile_size: 256
root_dir: C:\Users\adm.nkiner\Documents\BEAM\app\beam_update_2309\beam_model_training\tests\satellite
seed: 2022
test:
  model_version: U-Net_20240117-1630
test_size: 0.2
# MODEL SETTINGS
train:
  architecture: U-Net
  backbone: resnet18
  epochs: 10
  loss_function: None
training: true
