---
# Template configuration for experiments.
# Update for general changes, or make a copy for experiments.
# GENERAL SETTINGS
codes: ["Background", "Building"]
# DATA SETTINGS
erosion: true
root_dir: F:\SanSalvador_model
seed: 2022
test:
  model_version: U-Net_20241117-1410
test_size: 0.2
tile_size: 512
# MODEL SETTINGS
train:
  architecture: U-Net
  backbone: resnet50
  epochs: 300
  loss_function: CrossCombinedLoss
training: true
