---
# Template configuration for experiments.
# Update for general changes, or make a copy for experiments.
# GENERAL SETTINGS
codes: ["Background", "Building"]
# DATA SETTINGS
tiling:
  distance_weighting: false
  create_tile_shp: false
  erosion: true
  tile_size: 512
root_dir: F:/dev_versions/SanSalvador_model_PAN
seed: 2022
test:
  model_version: U-Net_20240124-1009
test_size: 0.2
# MODEL SETTINGS
train:
  architecture: U-Net
  backbone: resnet18
  epochs: 300
  loss_function: None
training: true
